#pragma once
#include <PlayerComponent.h>
#include <PositionComponent.h>
#include <VelocityComponent.h>
#include <RectComponent.h>
#include <ControllerComponent.h>
#include "AccelerationComponent.h"
#include "ABAcomponent.h"
#include "HealthComponent.h"
#include "InflictAbilityComponent.h"
